apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nilin.fullname" . }}-secrets
type: Opaque
stringData:
  mongodb-uri: {{ required "mongodb.uri is required" .Values.secrets.mongodbUri }}
  redis-url: {{ required "redis.url is required" .Values.secrets.redisUrl }}
  jwt-secret: {{ required "jwt.secret is required" .Values.secrets.jwtSecret }}
  stripe-secret: {{ required "stripe.secret is required" .Values.secrets.stripeSecret }}
