from pathlib import Path

O, C = "<div", "</motion>".replace("motion", "div")  # closing tag

def tag(attrs=""):
    return f"{O}{attrs}>"

def close():
    return C + ">"

# Build default variant as list of lines (no accidental typos)
lines = [
  "  // Default variant — mobile: horizontal list card; lg+: vertical grid card",
  "  return (",
  f"    {tag()}",
  "      onClick={handleClick}",
  "      role=\"button\"",
  "      tabIndex={0}",
  "      onKeyDown={(e) => {",
  "        if (e.key === 'Enter' || e.key === ' ') {",
  "          e.preventDefault();",
  "          handleClick();",
  "        }",
  "      }}",
  "      className=\"w-full text-left bg-white rounded-2xl border border-[#E8E4E0] overflow-hidden group cursor-pointer",
  "        transition-all duration-300 ease-out max-lg:flex max-lg:flex-row max-lg:items-stretch lg:block",
  "        hover:shadow-[0_8px_30px_rgba(232,180,168,0.15)] lg:hover:-translate-y-1",
  "        focus:outline-none focus:ring-2 focus:ring-[#E8B4A8]/30\"",
  "    >",
  f"      {tag(' className={`relative shrink-0 max-lg:w-[108px] max-lg:min-h-[120px] lg:w-full h-36 lg:h-48 ${gradientClass} overflow-hidden`}')}",
  "        {service.image ? (",
  "          <img",
  "            src={service.image}",
  "            alt={displayTitle}",
  "            loading=\"lazy\"",
  "            className=\"w-full h-full object-cover lg:group-hover:scale-110 transition-transform duration-500\"",
  "          />",
  "        ) : (",
  f"          {tag(' className=\"w-full h-full flex items-center justify-center min-h-[120px] lg:min-h-0\"')}",
  "            <Sparkles className=\"w-8 h-8 lg:w-10 lg:h-10 text-[#E8B4A8]/50\" aria-hidden />",
  f"          {close()}",
  "        )}",
  f"        {tag(' className=\"absolute inset-x-2 top-2 flex items-start justify-between gap-1 pointer-events-none\"')}",
  f"          {tag(' className=\"flex flex-col gap-1 pointer-events-auto min-w-0\"')}",
  "            {service.isFeatured && (",
  "              <span className=\"bg-[#D4A89A] text-white text-[10px] lg:text-xs font-semibold px-2 py-0.5 rounded-full flex items-center gap-0.5 shadow-sm w-fit\">",
  "                <TrendingUp className=\"h-2.5 w-2.5 shrink-0\" />",
  "                Featured",
  "              </span>",
  "            )}",
  "            {service.isNew && (",
  "              <span className=\"bg-[#7BA889] text-white text-[10px] lg:text-xs font-semibold px-2 py-0.5 rounded-full shadow-sm w-fit\">",
  "                NEW",
  "              </span>",
  "            )}",
  f"          {close()}",
  "          {displayRating > 0 && (",
  f"            {tag(' className=\"bg-white/95 backdrop-blur-sm px-1.5 py-0.5 lg:px-2.5 lg:py-1 rounded-full flex items-center gap-0.5 lg:gap-1.5 shadow-sm pointer-events-auto shrink-0\"')}",
  "              <Star className=\"h-3 w-3 lg:h-4 lg:w-4 fill-[#E8B4A8] text-[#E8B4A8]\" />",
  "              <span className=\"text-[10px] lg:text-sm font-semibold text-[#2D2D2D]\">{displayRating.toFixed(1)}</span>",
  "              {ratingCount > 0 && (",
  "                <span className=\"hidden lg:inline text-xs text-[#6B6B6B]\">({ratingCount})</span>",
  "              )}",
  f"            {close()}",
  "          )}",
  f"        {close()}",
  "        <button",
  "          type=\"button\"",
  "          onClick={handleToggleFavorite}",
  "          className={`absolute bottom-2 right-2 lg:top-3 lg:left-3 lg:bottom-auto lg:right-auto p-1.5 lg:p-2 rounded-full shadow-sm transition-all pointer-events-auto ${",
  "            isFavorited",
  "              ? 'bg-red-500 text-white'",
  "              : 'bg-white/90 backdrop-blur-sm text-gray-600 hover:bg-white'",
  "          } ${isToggling ? 'opacity-50' : ''}`}",
  "          aria-label={isFavorited ? 'Remove from favorites' : 'Add to favorites'}",
  "        >",
  "          <Heart className={`h-3.5 w-3.5 lg:h-4 lg:w-4 ${isFavorited ? 'fill-current' : ''}`} />",
  "        </button>",
  f"      {close()}",
  f"      {tag(' className=\"flex flex-col flex-1 min-w-0 p-3 lg:p-4 max-lg:justify-between\"')}",
  f"        {tag()}",
  "          <span className=\"inline-block px-2 py-0.5 bg-[#F8F6F4] text-[#6B6B6B] text-[10px] lg:text-xs font-medium rounded-md mb-1.5 lg:mb-2\">",
  "            {service.category}",
  "          </span>",
  "          <h3 className=\"font-semibold text-[#2D2D2D] text-sm lg:text-base mb-1 lg:mb-2 line-clamp-2 leading-snug group-hover:text-[#D4A89A] transition-colors\">",
  "            {displayTitle}",
  "          </h3>",
  "          {service.description && (",
  "            <p className=\"hidden lg:block text-sm text-[#6B6B6B] mb-3 line-clamp-2\">",
  "              {service.description}",
  "            </p>",
  "          )}",
  "          {service.duration && (",
  f"            {tag(' className=\"flex items-center gap-1 text-xs text-[#6B6B6B] mb-2 lg:hidden\"')}",
  "              <Clock className=\"h-3.5 w-3.5 text-[#D4A89A]\" />",
  "              <span>{service.duration} min</span>",
  f"            {close()}",
  "          )}",
  f"          {tag(' className=\"hidden lg:flex items-center gap-4 text-sm text-[#6B6B6B] mb-3\"')}",
  "            {service.duration && (",
  f"              {tag(' className=\"flex items-center gap-1.5\"')}",
  "                <Clock className=\"h-4 w-4 text-[#D4A89A]\" />",
  "                <span>{service.duration} min</span>",
  f"              {close()}",
  "            )}",
  "            {service.provider?.location && (",
  f"              {tag(' className=\"flex items-center gap-1.5 min-w-0\"')}",
  "                <MapPin className=\"h-4 w-4 text-[#D4A89A] shrink-0\" />",
  "                <span className=\"truncate\">{service.provider.location}</span>",
  f"              {close()}",
  "            )}",
  f"          {close()}",
  f"        {close()}",
  f"        {tag(' className=\"flex items-center justify-between gap-2 pt-2 lg:pt-3 border-t border-[#E8E4E0] max-lg:mt-1\"')}",
  f"          {tag(' className=\"min-w-0\"')}",
  "            {service.provider && (",
  "              <p className=\"text-[10px] lg:text-xs text-[#9B9B9B] mb-0.5 truncate hidden lg:block\">by {service.provider.name}</p>",
  "            )}",
  f"            {tag(' className=\"flex items-baseline gap-1 flex-wrap\"')}",
  "              <span className=\"text-base lg:text-xl font-bold text-[#2D2D2D]\">AED {displayPrice}</span>",
  "              <span className=\"text-[10px] lg:text-xs text-[#9B9B9B]\">/ service</span>",
  f"            {close()}",
  f"          {close()}",
  "          <button",
  "            type=\"button\"",
  "            onClick={(e) => {",
  "              e.stopPropagation();",
  "              handleClick();",
  "            }}",
  "            className=\"shrink-0 px-3.5 py-2 lg:px-4 lg:py-2 bg-[#E8B4A8] text-white font-medium text-xs lg:text-sm rounded-lg hover:bg-[#D4A89A] active:scale-95 transition-all\"",
  "          >",
  "            Book",
  "          </button>",
  f"        {close()}",
  f"      {close()}",
  f"    {close()}",
  "  );",
]

block = "\n".join(lines) + "\n"

card_path = Path(__file__).resolve().parent.parent / "src/components/customer/ServiceCard.tsx"
s = card_path.read_text(encoding="utf-8")

start = s.index("  // Default variant")
end = s.index("\n};\n\nexport default", start)

# Also add Sparkles import if missing
if "Sparkles" not in s:
    s = s.replace(
        "import { Star, Clock, MapPin, TrendingUp, ChevronRight, Heart } from 'lucide-react';",
        "import { Star, Clock, MapPin, TrendingUp, ChevronRight, Heart, Sparkles } from 'lucide-react';",
    )

s = s[:start] + block + s[end:]
card_path.write_text(s, encoding="utf-8")
print("patched ok, block lines:", len(lines))
