apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nilin-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
    - hosts:
        - api.nilin.app
        - app.nilin.app
      secretName: nilin-tls
  rules:
    - host: api.nilin.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nilin-api
                port:
                  number: 10000
    - host: app.nilin.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nilin-frontend
                port:
                  number: 80
