apiVersion: apps/v1
kind: Deployment
metadata:
  name: nilin-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nilin
      component: redis
  template:
    metadata:
      labels:
        app: nilin
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          command: ["redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru", "--appendonly", "yes"]
