apiVersion: v1
kind: ServiceAccount
metadata:
  name: nilin-api
  namespace: nilin
  labels:
    app: nilin-api
  annotations:
    iam.gke.io/gcp-service-account: IAM_REZUL007
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nilin-worker
  namespace: nilin
  labels:
    app: nilin-worker
  annotations:
    iam.gke.io/gcp-service-account: IAM_REZUL007
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nilin-scheduler
  namespace: nilin
  labels:
    app: nilin-scheduler
  annotations:
    iam.gke.io/gcp-service-account: IAM_REZUL007
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nilin-frontend
  namespace: nilin
  labels:
    app: nilin-frontend
  annotations:
    iam.gke.io/gcp-service-account: IAM_REZUL007
