apiVersion: v1
kind: ServiceAccount
metadata:
  name: nilin-api
  namespace: nilin
  labels:
    app: nilin-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nilin-worker
  namespace: nilin
  labels:
    app: nilin-worker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nilin-scheduler
  namespace: nilin
  labels:
    app: nilin-scheduler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nilin-frontend
  namespace: nilin
  labels:
    app: nilin-frontend
