apiVersion: apps/v1
kind: Deployment
metadata:
  name: nilin-api
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nilin-worker
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nilin-frontend
spec:
  replicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nilin-api-hpa
spec:
  minReplicas: 2
  maxReplicas: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nilin-worker-hpa
spec:
  minReplicas: 2
  maxReplicas: 5
